hack_umbc/eportal/urls.py
from django.urls import path
from eportal import views

app_name = 'eportal'

urlpatterns = [
    path('',views.index,name="home"),
    path('ocr/',views.ocr_page,name="ocr_page"),
    path('ocr_output/',views.ocr_output,name="ocr_output"),
    path('synthesizer/',views.synthesizer,name="synthesizer"),
    path('our_vision/',views.our_vision,name="our_vision"),
]

hack_umbc/hack_umbc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eportal.urls')),
]

hack_umbc/eportal/models.py
from django.db import models

# Create your models here.

hack_umbc/eportal/views.py
from django.shortcuts import render
from .ocr import main_url
# Create your views here.

def ocr_page(request):
    return render(request, 'eportal/ocr_form.html', {})

def ocr_output(request):
    if request.method == "POST":
        if 'ocr_file' in request.FILES:
            file = request.FILES['ocr_file']
            final_output = main_url(file)
            text = ''
            for output in final_output:
                text = text + output
            return render(request,'eportal/ocr_output.html',{'output':text})

def index(request):
    return render(request,'eportal/index.html',{})

def synthesizer(request):
    return render(request,'eportal/synthsizer.html',{})

def our_vision(request):
    return render(request,'eportal/our_vision.html',{})    

hack_umbc/templates/eportal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Saarthi</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/annyang/2.6.1/annyang.min.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css_content %}
    {% endblock %}
</head>

<body>
    <nav>
        <label class="logo"><a href="{% url 'eportal:home' %}" id="home_page">
                <p>SAARTHI</p>
            </a></label>
        <ul class="nav-links">
            <li id="toau"><a href="{% url 'eportal:ocr_page' %}" id="revoice_page">
                    <p>Revoice</p>
                </a></li>
            <li id="todom"><a href="{% url 'eportal:synthesizer' %}" id="synthesiser_page">
                    <p>Voice Synthesiser</p>
                </a></li>
            <li id="todom"><a href="{% url 'eportal:our_vision' %}" id="our_vision">
                    <p>Our Vision</p>
                </a></li>
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <script src="{% static 'js/app.js' %}"></script>
    <script>
        AOS.init();
    </script>

</body>

</html>

hack_umbc/templates/eportal/index.html
{% extends 'eportal/base.html' %}
{% load static %}
{% block content %}
<button onclick="speakcommand()" id="myBtn" title="Voice Controller"><i class="fas fa-microphone"></i></button>
<div class="banner">
    <img class="banner_background" src="{% static 'images/landing.jpg' %}" alt="">
    <div class="content">
        <h1 data-aos="fade-down" data-aos-duration="1000">Saarthi</h1>
        <p data-aos="fade-up" data-aos-duration="1000">An online education portal for the visually impaired</p>
    </div>
</div>

<div class="aboutus">
    <div class="container">
        <div class="heading">
            <h1 data-aos="fade-right" data-aos-delay="50">About Saarthi</h1>
        </div>
        <div class="aboutcont">
            <p data-aos="fade-right" data-aos-delay="100">Majority of education and textbooks never reach the visually impaired, leaving them behind in the lore of literacy. Introducing SAARTHI, a platform for the education of visually impaired. During this period of pandemic the visually impaired don’t have any kind of access to Physical education. Hence,  a need of a portal arises via which these people could continue their education. With SAARTHI we want to give them the right to education. These people who are left out, will get the resources and the opportunity to gain knowledge from all the available text books out there. This is a school of hard knocks with a ride in the short bus. This just doesn’t stick to this pandemic period, rather it also extends to help out those children as well who are not in an able condition to move to their place of education.</p>
            <p data-aos="fade-right" data-aos-delay="100">“It shouldn’t matter how slowly some children learn as long as we are encouraging them not to stop.” – Robert John Meehan</p>
        </div>
    </div>
</div>

<div class="cards_section">
    <div class="row">
        <div class="col-md-12 col-lg-4">
            <div class="view view-first" data-aos="zoom-out-left" data-aos-delay="50" data-aos-duration="1500">
                <img src="{% static 'images/card1.jpg' %}" />
                <div class="mask">
                    <h2>WHY</h2>
                    <p>To help the Visually Impaired Students continue their education from any remote location and get access to the right to education. The kids should not feel that education is a chore, rather should feel it is a game of fun.</p>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-4">
            <div class="view view-first" data-aos="zoom-out-up" data-aos-delay="100" data-aos-duration="1500">
                <img src="{% static 'images/card2.jpg' %}" />
                <div class="mask">
                    <h2>NEED</h2>
                    <p>Education is vital for the development of any country. It provides change in the society and empowers people to achieve the impossible. We believe no one should be limited by their physical conditions to bring empowerment, as every mind is exceptional and equally curious.</p>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-4">
            <div class="view view-first" data-aos="zoom-out-right" data-aos-delay="150" data-aos-duration="1500">
                <img src="{% static 'images/card3.jpg' %}" />
                <div class="mask">
                    <h2>FOR</h2>
                    <p>We primarily focus on the visually impaired students, but it also helps those who have a difficulty in hearing and speaking as well.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="parallax pic">
    <div class="content" data-aos="fade-up">
        <div class="heading" data-aos="fade-up" data-aos-delay="50" data-aos-duration="1000">
            <h1>ReVoice</h1>
        </div>
        <div class="descr" data-aos="fade-up" data-aos-delay="100" data-aos-duration="1000">
            <p>A tool for the visually impaired, in their journey of accomplishments. Revoice will convert any material from a book to an audiobook. Now they never have to miss out on any knowledge, from the bed times stories to the Shakespeare’s lore.
            </p>
        </div>
    </div>
</div>

<div class="features">
    <div class="heading" data-aos="fade-right" data-aos-delay="50" data-aos-duration="1000">
        <h1>FEATURES</h1>
    </div>

    <div class="revoice">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="revoice-img" data-aos="fade-right" data-aos-delay="50" data-aos-duration="1000">
                        <img src="{% static 'images/revoice.svg' %}" alt="revoice">
                    </div>
                </div>
                <div class="col-12 col-md-6" data-aos="fade-left" data-aos-delay="50" data-aos-duration="1000">
                    <h1>Revoice</h1>
                    <br>
                    <p>A tool for the visually impaired, in their journey of accomplishments. Revoice will convert any material from a book to an audiobook. Now they never have to miss out on any knowledge, from the bed times stories to the Shakespeare’s lore.</p>
                    <br>
                    <a href="{% url 'eportal:ocr_page' %}">
                        <p id="revoice-button">Discover More</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="texttospeech">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6" data-aos="fade-right" data-aos-delay="100" data-aos-duration="1000">
                    <div class="text-content">
                        <h1>Speech To Text</h1>
                        <br>
                        <p>Never need to worry about writing, with this tool we want to empower these young minds to write what is in their mind through their voice. The tool will convert your voice to text.</p>
                        <br>
                        <a href="{% url 'eportal:synthesizer' %}">
                            <p id="revoice-button">Discover More</p>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="revoice-img" data-aos="fade-left" data-aos-delay="100" data-aos-duration="1000">
                        <img src="{% static 'images/speech-to-text.svg' %}" alt="speech-to-text">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="revoice">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="revoice-img" data-aos="fade-right" data-aos-delay="150" data-aos-duration="1000">
                        <img src="{% static 'images/write.svg' %}" alt="speechtotext">
                    </div>
                </div>
                <div class="col-12 col-md-6" data-aos="fade-left" data-aos-delay="150" data-aos-duration="1000">
                    <h1>Text To Speech</h1>
                    <br>
                    <p>A tool for people who cannot speak, imparting them a voice to express their views. </p>
                    <br>
                    <a href="{% url 'eportal:synthesizer' %}">
                        <p id="revoice-button">Discover More</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="texttospeech">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6" data-aos="fade-right" data-aos-delay="200" data-aos-duration="1000">
                    <div class="text-content">
                        <h1>Voice Controllable Portal</h1>
                        <br>
                        <p>This feature will allow the people to navigate the website and excess all the tools which provide education to them. Giving a seamless experience to the people. </p>
                        <br>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="revoice-img" data-aos="fade-left" data-aos-delay="200" data-aos-duration="1000">
                        <img src="{% static 'images/websites.svg' %}" alt="speech-to-text">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="footer">
    <h5>Made in HackUMBC 2020 by team index.html</h5>
</div>
<script src="{% static 'js/home_page.js' %}"></script>
{% endblock %}

hack_umbc/templates/eportal/ocr_form.html
{% extends 'eportal/base.html' %}
{% load static %}
{% block css_content %}
<link rel="stylesheet" href="{% static 'css/ocr_form.css' %}">
{% endblock %}
{% block content %}
<button onclick="speakcommand()" id="myBtn" title="Voice Controller"><i class="fas fa-microphone"></i></button>
<div class="banner">
    <img class="banner_background" src="{% static 'images/ocr_form.jpg' %}" alt="">
    <div class="content">
        <div class="ocr_form">
            <div class="container">
                <h1>Revoice</h1>
                <p>Ocr based feature to convert your uploaded pdf file into audio book.</p>
                <br>
                <form action="{% url 'eportal:ocr_output' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="file">Upload File (Max-pages: 10):</label>
                    <input type="file" id="file" name="ocr_file" accept="application/pdf" />
                    <br>
                    <input type="submit" name="" value="submit" class="submit-button" id="submit">
                </form>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/ocr_form.js' %}"></script>
{% endblock %}

hack_umbc/templates/eportal/ocr_output.html
{% extends 'eportal/base.html' %}
{% load static %}
{% block css_content %}
<link rel="stylesheet" href="{% static 'css/ocr_output.css' %}" />
{% endblock %}
{% block content %}
<script src="{% static 'js/annyang.min.js' %}"></script>
<button onclick="speakcommand()" id="myBtn" title="Voice Controller"><i class="fas fa-microphone"></i></button>
<div class="ocr_output">
    <div class="container">
        <pre class="text_output" id="text_output">{{ output }}</pre>
        <button type="button" onclick="textToAudio()">Speak</button>
        <button type="button" onclick="pauseAudio()">Pause</button>
        <button type="button" onclick="resumeAudio()">Resume</button>
        <button type="button" onclick="cancelAudio()">Stop</button>
    </div>
</div>

<script src="{% static 'js/ocr_output.js' %}"></script>

{% endblock %}

hack_umbc/templates/eportal/our_vision.html
{% extends 'eportal/base.html' %}
{% load static %}
{% block css_content %}
<link rel="stylesheet" href="{% static 'css/our_vision.css' %}" />
{% endblock %}
{% block content %}
<button onclick="speakcommand()" id="myBtn" title="Voice Controller"><i class="fas fa-microphone"></i></button>
<div class="our_vision">
    <div class="our_vision_heading" data-aos="fade-right" data-aos-delay="50" data-aos-duration="1000">
        <h1>Our Vision</h1>
    </div>
    <div class="our_content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="vision-img" data-aos="fade-right" data-aos-delay="50" data-aos-duration="1000">
                        <img src="{% static 'images/vision.svg' %}" alt="revoice">
                    </div>
                </div>
                <div class="col-12 col-md-6" data-aos="fade-left" data-aos-delay="50" data-aos-duration="1000">
                    <h1>What we See</h1>
                    <br>
                    <p>As Malala Yousafzai has said, “One child, one teacher, one pen and one book can change the world.” We want to be part of that change, doing our bit. Most people see what is, and never see what can be. In this world, many of the young minds are left behind, no one telling them that there is no such thing as a stupid question. Unable to search for the answers of those, We want to change that. Giving a platform for these beautiful minds that are unable to see the artistry of life, missing out on those fantasies which our childhood has gone by reading.
                    </p>
                    <p>With this platform our aim is to give these young kids a chance to experience the same which you and I have experienced in our childhood. They never need to let go or compromise on the knowledge needed to learn, knowing that there is a SAARTHI (A Companion).</p>
                    <p>We wish to light a beacon of hope for these kids, to let them accomplish and experience the mystifying journey, that is our life</p>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/our_vision.js' %}"></script>

{% endblock %}

hack_umbc/templates/eportal/synthsizer.html
{% extends 'eportal/base.html' %} {% load static %} {% block css_content %}
<link rel="stylesheet" href="{% static 'css/synthesizer.css' %}" />
{% endblock %} {% block content %}
<button onclick="speakcommand()" id="myBtn" title="Voice Controller"><i class="fas fa-microphone"></i></button>
<div class="banner">
    <img class="banner_background" src="{% static 'images/img41.jpg' %}" alt="" />
    <div class="content">
        <div class="speech-writer-content">
            <div class="container">
                <h3 class="text-center">Voice Synthesizer</h3>
                <div id="info"></div>
                <div class="float-right">
                    <button id="start_button">
                        <img id="start_img" src="{% static 'images/mic.gif' %}" alt="Start" />
                    </button>
                </div>
                <div id="results">
                    <span id="final_span" class="final"></span>
                    <span id="interim_span" class="interim"></span>
                    <p></p>
                </div>

                <div class="row">
                    <div class="col-12 col-md-8 col-lg-4">
                        <select id="select_language"></select>
                    </div>
                    <div class="col-12 col-md-8 col-lg-4">
                        <select id="select_dialect"></select>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-12 col-md-8 col-lg-4">
                        <button id="copy_button" class="btn btn-primary">Copy</button>
                    </div>
                    <div class="col-12 col-md-8 col-lg-4">
                        <button class="btn btn-primary" onclick="speakcommand()">
                            Speak Command
                        </button>
                    </div>
                    <div class="col-12 col-md-8 col-lg-4">
                        <button class="btn btn-primary" onclick="readcommand()">
                            Read Content
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/languages.js' %}"></script>
<script src="{% static 'js/speech.js' %}"></script>

{% endblock %}